name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for package.json
        id: check_package
        run: |
          if [ ! -f package.json ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "No root package.json found, skipping lint"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Node.js
        if: steps.check_package.outputs.skip == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        if: steps.check_package.outputs.skip == 'false'
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Run linter
        if: steps.check_package.outputs.skip == 'false'
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for package.json
        id: check_package
        run: |
          if [ ! -f package.json ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "No root package.json found, skipping test"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Node.js
        if: steps.check_package.outputs.skip == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        if: steps.check_package.outputs.skip == 'false'
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Run tests
        if: steps.check_package.outputs.skip == 'false'
        run: npm test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for package.json
        id: check_package
        run: |
          if [ ! -f package.json ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "No root package.json found, skipping build"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Node.js
        if: steps.check_package.outputs.skip == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        if: steps.check_package.outputs.skip == 'false'
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Build application
        if: steps.check_package.outputs.skip == 'false'
        run: npm run build

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for package.json
        id: check_package
        run: |
          if [ ! -f package.json ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "No root package.json found, skipping security scan"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Node.js
        if: steps.check_package.outputs.skip == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        if: steps.check_package.outputs.skip == 'false'
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Run npm audit
        if: steps.check_package.outputs.skip == 'false'
        run: npm audit --audit-level=high || true
